### PR TITLE
add Arch Linux install instructions

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by icholy** [comment]
The version on aur is pretty old. Any way we can update it?

**Comment by icholy** [comment]
nvm, I'm thinking about the wroing project :laughing:

**Comment by polyzen** [comment]
Perhaps this section should be moved higher (to keep alphabetical order)?

Also considering adding a requirements section as the AUR package received a comment asking to add xorg-xwd as a dep, although I didn't gather that from the README. Is xorg-xwd actually necessary?

**Comment by icholy** [comment]
Yeah, `xwd` is required. It's not mentioned in the instructions for the other distros because it's usually installed by default.

**Comment by polyzen** [comment]
Okay, I'll just add it to the PKGBUILD, then.

**Comment by icholy** [comment]
Sounds good, thanks for the contribution.

**Pull request merged**
