### PR TITLE
Add `help` and `version` command

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by icholy** [comment]
dope :+1:

**Comment by SimenB** [comment]
@icholy Could you make a release so we can use these as tests in the homebrew formula?

**Comment by icholy** [comment]
@SimenB yeah sure, probably not until Monday though.

**Comment by SimenB** [comment]
@icholy ping 😄

**Comment by icholy** [comment]
@SimenB done. Sorry for the wait, titanfall 2 is ruining my life.

**Pull request merged**
